name: PHP code style

on:
  push:
    paths:
      - '**.php'
      - 'composer.json'
      - 'composer.lock'
      - '.github/workflows/fix-php-code-style-issues.yml'
  pull_request:
    paths:
      - '**.php'
      - 'composer.json'
      - 'composer.lock'
      - '.github/workflows/fix-php-code-style-issues.yml'

permissions:
  contents: read

jobs:
  php-code-style:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      - name: Install composer dependencies
        run: composer update --prefer-stable --prefer-dist --no-interaction -W

      - name: Check PHP code style
        run: vendor/bin/pint --test
